dist: xenial
sudo: required

language: c ruby
rvm:
  - "2.6"

install:
  - sudo apt-get install gcc
  - gem install rake
  - gem install ceedling

script:
  - cd test/unit-test/test_embclib/
  - ceedling test:all