@startuml ctype

class ctype << typedef >>
{
  + IsAlpha(uint8_t) : bool_et
  + IsDigit(uint8_t) : bool_et
  + IsAlphaNumeric(uint8_t) : bool_et
  + IsControl(uint8_t) : bool_et
  + IsAscii(uint8_t) : bool_et
  + IsGraph(uint8_t) : bool_et
  + IsLower(uint8_t) : bool_et
  + IsPunct(uint8_t) : bool_et
  + IsHexDigit(uint8_t) : bool_et
  + IsPrintable(uint8_t) : bool_et
  + IsSpace(uint8_t) : bool_et
  + IsUpper(uint8_t) : bool_et
  + ToUpper(uint8_t) : uint8_t
  + ToLower(uint8_t) : uint8_t
}

hide ctype attribute

@enduml