@startuml types-library

!include inttype.puml

class types << typedef >>
{
  + bool_et : bool_e
  + state_et : state_e
  + status_et : Status_e

  + IsAlpha(uint8_t) : bool_et
  + IsDigit(uint8_t) : bool_et
  + IsAlphaNumeric(uint8_t) : bool_et
  + IsControl(uint8_t) : bool_et
  + IsAscii(uint8_t) : bool_et
  + IsGraph(uint8_t) : bool_et
  + IsLower(uint8_t) : bool_et
  + IsPunct(uint8_t) : bool_et
  + IsHexDigit(uint8_t) : bool_et
  + IsPrintable(uint8_t) : bool_et
  + IsSpace(uint8_t) : bool_et
  + IsUpper(uint8_t) : bool_et
  + ToUpper(uint8_t) : uint8_t
  + ToLower(uint8_t) : uint8_t
}

enum bool_e
{
    FALSE
    TRUE
}

enum state_e
{
    LOW
    HIGH
}

enum status_e
{
    FAILED,
    SUCCESS,
    BUSY,
    TIMEOUT
}

hide enum method

inttype -up-> types
bool_e -up-> types
state_e -up-> types
status_e -up-> types


@enduml