@startuml utility-library

class utils
{
  .. Macro functions ..
  + Abs(val)
  + Max(val1, val2) 
  + Min(val1, val2)
  + Pow2(val)
  + Swap(val1, val2)
  + Limit(val, min, max)
  --
  + UTILS_Rand(min : int16_t, max : int16_t) : int16_t
  + UTILS_RandSeed(seed_i16 : uint16_t) : void
  + UTILS_Scale(in_value : int16_t, 
                in_min : int16_t, in_max : int16_t, 
                out_min : int16_t, out_max : int16_t) : int16_t

}

@enduml